### ISSUE TITLE
Show guidance on hover

### ISSUE THREAD

**Issue by janpipek** [natl/language-geant4-macro#6]
Hi, nice job!

Would it be possible (or is it using some keyboard shortcut?) to display the guidance for an already written command on hover/click/other user action? It would make understanding macro files much easier.

**Comment by natl** [comment]
Do you mean something like this: https://atom.io/packages/hover-tooltips-hdevtools

It is almost definitely possible. Good idea.

**Comment by janpipek** [comment]
Yes, this looks nice.

**Comment by natl** [comment]
What do you think of this as a solution??

![tooltip](https://cloud.githubusercontent.com/assets/2887977/18610840/49058054-7d27-11e6-820d-438f00f2a5fb.gif)

**Comment by janpipek** [comment]
That looks absolutely brilliant :-)

**Comment by natl** [comment]
Feature added with #10 
Closing Issue.

**Comment by janpipek** [comment]
I was about to file a bug report. And then I realized that I still have atom 1.2 (statically installed from .rpm). So instead, I can report that it really works.

**Comment by natl** [comment]
Awesome, thanks for the confirmation. If you find it doesn't work with early atom versions, let me know and I'll change the compatibility list.

**Comment by janpipek** [comment]
Eh, in 1.10 it works, in 1.2 it doesn't (I mean, the hovering, tab-completion is ok in both). Quite a broad span ;-)
